export const FETCH_REPOSITORY_REQUEST = "FETCH_REPOSITORY_REQUEST";
export const FETCH_REPOSITORY_SUCCESS = "FETCH_REPOSITORY_SUCCESS";
export const FETCH_REPOSITORY_FAILURE = "FETCH_REPOSITORY_FAILURE";
